services:
  api: &api
    image: ghcr.io/vitorvezani/rinha-de-backend-2025-go:latest
    hostname: api
    environment:
      - APP_PORT=9999
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - WORKER_CONCURRENCY=16
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=rinha
    depends_on:
      - postgres
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "350MB"

  api2:
    <<: *api
    hostname: api2

  nginx:
    image: nginx:latest
    hostname: nginx
    depends_on:
      - api
      - api2
    ports:
      - "9999:80"

  postgres:
    image: postgres:16
    hostname: postgres
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
